### ISSUE TITLE
vortex

### ISSUE THREAD

**Issue by deadlyaaher** [thevortex/Fizzix#1]
are you still around its aaher2 from back in foxtopia days

**Comment by mosesnunez** [comment]
Hi, I am. What brought you to check on that old forum?

**Comment by deadlyaaher** [comment]
Recently got back around to getting into pc, and was looking if the foxtopia guys were all still around

**Comment by thevortex** [comment]
yo dude! ya we got a discord set up, will send the link into this thread in
a day or two, i am on the road doing a little trip this weekend but will be
home tuesday and send ya that

V

Sent from my iPad

On May 12, 2019, at 4:49 PM, aaher3 <notifications@github.com> wrote:

Recently got back around to getting into pc, and was looking if the
foxtopia guys were all still around

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/thevortex/Fizzix/issues/1#issuecomment-491635940>, or mute
the thread

**Comment by deadlyaaher** [comment]
Sweet as bud, can’t wait

**Comment by deadlyaaher** [comment]
You back yet bud hahah

**Comment by thevortex** [comment]
https://discord.gg/x45ws5
